# Generated by Django 3.0.5 on 2020-05-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'beverages',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'dscriptions',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('natrium_mg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('saturated_fat_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sugars_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('caffein_mg', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Category')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(max_length=1000)),
                ('Beverage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Beverage')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='BeverageSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beverage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Beverage')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Size')),
            ],
            options={
                'db_table': 'beverages_allegies',
            },
        ),
        migrations.CreateModel(
            name='BeverageAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Allergy')),
                ('Beverage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Beverage')),
            ],
            options={
                'db_table': 'beverages_allergies',
            },
        ),
        migrations.AddField(
            model_name='beverage',
            name='allergy',
            field=models.ManyToManyField(through='beverage.BeverageAllergy', to='beverage.Allergy'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Category'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Description'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.Nutrition'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='size',
            field=models.ManyToManyField(through='beverage.BeverageSize', to='beverage.Size'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverage.SubCategory'),
        ),
    ]
